global using Azure.Storage.Queues;
global using FluentValidation;
global using Microsoft.EntityFrameworkCore;
global using Ordering.Job.Domain.AggregatesModel.OrderingJobAggregates;
global using Ordering.Job.Domain.Exceptions;
global using Ordering.Job.Domain.Messages;
global using Ordering.Job.Infrastructure.Repositories;
global using Ordering.Job.Infrastructure;
global using Ordering.Job.Scheduler.Complete;